"""Materialise an environment into a visible, read-only snapshot under `envs/<name>/`.

An environment is defined by composable source — a warehouse shape (a preset), its docs, and a
semantic layer. This renders those into one directory a reader can open and see whole, WITHOUT
forking the source: the snapshot is GENERATED and regeneratable, so it cannot silently drift from the
base. (That forking is exactly what study 01 was burned by — four copies of the layer, one of which
quietly acquired a question-matching synonym list that survived the run and the review.) The
committed snapshot is kept honest by a test that regenerates it and compares, so a change to the
source that is not re-materialised fails loudly rather than leaving a stale env in the tree.

One env directory per experiment/study; each is a view of composable source, never a hand-edited copy.
"""

from __future__ import annotations

from pathlib import Path

import harness_paths
from semantic.semantic import SPEC_PATH as DEFAULT_LAYER
from warehouse.environment import build

_GENERATED = "GENERATED by `python -m env_snapshot` from composable source — do not edit; regenerate."


def materialize_env(name: str, *, tables: str = "star_schema", docs: str = "star_schema",
                    layer: str | Path | None = None) -> Path:
    """Write a visible snapshot of one environment to `envs/<name>/` and return its path.

    `tables` / `docs` name warehouse presets (the shape and its COMMENT-ON docs); `layer` is the
    semantic-layer YAML (default: the engine's bundled governed layer). Nothing is executed and no
    DuckDB is built — the snapshot is the env's *definitions* (the shape, the docs, the metrics), the
    part a reader inspects; the live DuckDB is built from these plus raw data on demand."""
    layer_path = Path(layer) if layer else DEFAULT_LAYER
    env = build(None, name, {"tables": tables, "docs": docs})

    out = harness_paths.ROOT / "envs" / name
    out.mkdir(parents=True, exist_ok=True)
    warehouse_sql = f"-- {_GENERATED}\n\n{env.preset_sql}"
    if env.docs_sql:
        warehouse_sql += f"\n\n-- docs (COMMENT ON) --\n{env.docs_sql}"
    (out / "warehouse.sql").write_text(warehouse_sql)
    (out / "semantic_layer.yml").write_text(f"# {_GENERATED}\n{layer_path.read_text()}")
    (out / "README.md").write_text(
        f"# env: {name}\n\n{_GENERATED}\n\n"
        f"A visible, read-only snapshot of one environment — its definitions, generated from the\n"
        f"composable source so it cannot drift:\n\n"
        f"- **`warehouse.sql`** — the tables/views shape (preset `{tables}`) + docs (`{docs}`).\n"
        f"- **`semantic_layer.yml`** — the governed metric layer (`{layer_path.name}`).\n\n"
        f"The live DuckDB is built from this shape plus raw data on demand (it is not committed).\n")
    return out


def main() -> None:
    """Materialise the default environments the repo ships."""
    for spec in (dict(name="habit_tracking"),):
        path = materialize_env(**spec)
        print(f"materialised {path.relative_to(harness_paths.ROOT)}")


if __name__ == "__main__":
    main()
